# a wrapper for math package, not using is anymore but okay
import math
from functools import reduce

class Math:
    acos = lambda *x: math.acos(*x)
    acosh = lambda *x: math.acosh(*x)
    asin = lambda *x: math.asin(*x)
    asinh = lambda *x: math.asinh(*x)
    atan = lambda *x: math.atan(*x)
    atan2 = lambda *x: math.atan2(*x)
    atanh = lambda *x: math.atanh(*x)
    ceil = lambda *x: math.ceil(*x)
    copysign = lambda *x: math.copysign(*x)
    cos = lambda *x: math.cos(*x)
    cosh = lambda *x: math.cosh(*x)
    degrees = lambda *x: math.degrees(*x)
    e = math.e
    E = math.e
    erf = lambda *x: math.erf(*x)
    erfc = lambda *x: math.erfc(*x)
    exp = lambda *x: math.exp(*x)
    expm1 = lambda *x: math.expm1(*x)
    fabs = lambda *x: math.fabs(*x)
    factorial = lambda *x: math.factorial(*x)
    floor = lambda *x: math.floor(*x)
    fmod = lambda *x: math.fmod(*x)
    frexp = lambda *x: math.frexp(*x)
    fsum = lambda *x: math.fsum(*x)
    gamma = lambda *x: math.gamma(*x)
    gcd = lambda *x: math.gcd(*x)
    hypot = lambda *x: math.hypot(*x)
    inf = math.inf
    isclose = lambda *x: math.isclose(*x)
    isfinite = lambda *x: math.isfinite(*x)
    isinf = lambda *x: math.isinf(*x)
    isnan = lambda *x: math.isnan(*x)
    ldexp = lambda *x: math.ldexp(*x)
    lgamma = lambda *x: math.lgamma(*x)
    log = lambda *x: math.log(*x)
    log10 = lambda *x: math.log10(*x)
    log1p = lambda *x: math.log1p(*x)
    log2 = lambda *x: math.log2(*x)
    modf = lambda *x: math.modf(*x)
    nan = lambda *x: math.nan(*x)
    pi = math.pi
    pow = lambda *x: math.pow(*x)
    radians = lambda *x: math.radians(*x)
    remainder = lambda *x: math.remainder(*x)
    sin = lambda *x: math.sin(*x)
    sinh = lambda *x: math.sinh(*x)
    sqrt = lambda *x: math.sqrt(*x)
    tan = lambda *x: math.tan(*x)
    tanh = lambda *x: math.tanh(*x)
    tau = math.tau
    trunc = lambda *x: math.trunc(*x)
    mult = lambda *x: reduce((lambda x, y: x * y), x)
    add = lambda *x: reduce((lambda x, y: x + y), x)
    div = lambda x, y: x / y
    sub = lambda x, y: x - y